Errors improvement
gathuku/mpesa pull request #26
Opened 2022-11-15 17:10 UTC by Dev-Alchemist

2022-11-23 14:05 UTC, gathuku requested changes
Also i think we can add some tests here. so on this [file](https://github.com/gathuku/mpesa/blob/master/test/mpesa/resources/token_test.rb) add a test that check this 

```rb
def test raise_error_on_invalid_credentials
    client = Mpesa::Client.new(
      key: 'ZtkRW6ATbVtFpNml5w5SfG26Adfyagn9',
      secret: 'wrong_secret',
      env: 'sandbox',
      shortcode: '600998'
    )

  token_instance = Mpesa::Token.new(client)
  
  assert_raises(Mpesa::Error) do 
    token_instance.cache_token
  end
end

2022-11-23 14:05 UTC, gathuku commented on lib/mpesa/object.rb
> +      return unless attributes.is_a?(Hash)
```suggestion

```
@Dev-Alchemist  let get rid of this since we've handled the cause

2022-11-23 14:05 UTC, gathuku commented on lib/mpesa/resources/token.rb
> +      raise res.reason_phrase if res.body.empty?
```suggestion
      raise Error, res.reason_phrase if res.body.empty?
```
This will use the [custom error](https://github.com/gathuku/mpesa/blob/591f6290c2e64d242c00e6d649f403e1fc2ac282/lib/mpesa/error.rb#L4). The constant is [autoloaded](https://github.com/gathuku/mpesa/blob/591f6290c2e64d242c00e6d649f403e1fc2ac282/lib/mpesa.rb#L7) and will be available to code inside `Mpesa` module. This will raise `Mpesa::Error`

2022-11-23 14:17 UTC, gathuku commented
Also remember to update [CHANGELOG](https://github.com/gathuku/mpesa/blob/master/CHANGELOG.md) with this change

2022-11-26 16:12 UTC, Dev-Alchemist commented
Noted, let me update them.

2022-11-28 15:21 UTC, gathuku approved these changes

2022-11-28 15:36 UTC, gathuku requested changes

2022-11-28 15:36 UTC, gathuku commented on CHANGELOG.md
> +- Improve invalid credentials error messages
```suggestion
- Raise error on invalid oauth credentails
```

2022-11-28 15:38 UTC, gathuku commented
@Dev-Alchemist  change this message and check if test will run #28

2023-01-13 14:30 UTC, gathuku approved these changes

2023-01-13 14:30 UTC, merged